### ISSUE TITLE
Processing of class fields crashes, unpack error

### ISSUE THREAD

**Issue by isosphere** [isosphere/pyjavadisassemble#2]
```
Traceback (most recent call last):
  File "pyjavadisassemble.py", line 232, in <module>
    ProcessAttributes(attributes_count)
  File "pyjavadisassemble.py", line 123, in ProcessAttributes
    attribute_name_index = GetBytes('>H')
  File "pyjavadisassemble.py", line 116, in GetBytes
    return struct.unpack(data_format, classfile.read(struct.calcsize(data_format)))[0]
struct.error: unpack requires a string argument of length 2
```

**Comment by isosphere** [comment]
ProcessAttrributes() is trying to parse beyond the EOF
